before_script:
  - /usr/local/bin/python3.12 -m venv venv
  - source venv/bin/activate
  - /usr/local/bin/pip3 install -r requirements.txt
  - cd ./P7

lint-tests:
  tags:
    - fit2107
  script:
    - /usr/local/bin/python3.12 -m pylint tests/test_user_input.py

style-tests:
  tags:
    - fit2107
  script:
    - /usr/local/bin/python3.12 -m pycodestyle tests/test_user_input.py

test:
  tags:
    - fit2107
  script:
    - /usr/local/bin/python3.12 -m unittest -v